spring.datasource.url=jdbc:postgresql://localhost:5432/learn_db
spring.datasource.username=postgres
spring.datasource.password=PRATI17
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always